# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/htmlentities/all/htmlentities.rbi
#
# htmlentities-4.3.4

class HTMLEntities
  def decode(source); end
  def encode(source, *instructions); end
  def initialize(flavor = nil); end
end
class HTMLEntities::InstructionError < RuntimeError
end
class HTMLEntities::Encoder
  def basic_entity_regexp; end
  def build_basic_entity_encoder(instructions); end
  def build_extended_entity_encoder(instructions); end
  def contains_only_ascii?(string); end
  def encode(source); end
  def encode_decimal(char); end
  def encode_hexadecimal(char); end
  def encode_named(char); end
  def extended_entity_regexp; end
  def initialize(flavor, instructions); end
  def minimize_encoding(string); end
  def prepare(string); end
  def replace_basic(string); end
  def replace_extended(string); end
  def reverse_map; end
  def validate_instructions(instructions); end
end
class HTMLEntities::Decoder
  def decode(source); end
  def entity_regexp; end
  def initialize(flavor); end
  def prepare(string); end
end
module HTMLEntities::VERSION
end
class HTMLEntities::UnknownFlavor < RuntimeError
end
