# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yaml-front-matter/all/yaml-front-matter.rbi
#
# yaml-front-matter-0.0.1

module Psych
end
module Psych::FrontMatter
  def self.extract(content); end
end
