Gemspec/RequiredRubyVersion:
  Exclude:
    - 'frontman-ssg.gemspec'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/**/*'
    - 'project-templates/**/*'

Style/MethodMissingSuper:
  Exclude:
    - 'lib/**/*'

Metrics/MethodLength:
  Exclude:
    - 'lib/frontman/sitemap_tree.rb'
    - 'lib/frontman/data_store.rb'
    - 'lib/frontman/builder/builder.rb'
    - 'lib/frontman/commands/**/*'
    - 'lib/frontman/resource.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/frontman/sitemap_tree.rb'
    - 'lib/frontman/data_store.rb'
    - 'lib/frontman/builder/statistics_collector.rb'
    - 'lib/frontman/commands/**/*'
    - 'lib/frontman/resource.rb'

Style/ClassVars:
  Exclude:
    - 'lib/frontman/sitemap_tree.rb'
    - 'lib/frontman/bootstrapper.rb'
    - 'lib/frontman/config.rb'
    - 'lib/frontman/resource.rb'
    - 'lib/frontman/data_store_file.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/frontman/app.rb'
    - 'lib/frontman/builder/builder.rb'
    - 'lib/frontman/resource.rb'
    - 'lib/frontman/sitemap_tree.rb'

Style/ConditionalAssignment:
  Exclude:
    - 'lib/frontman/builder/builder.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/frontman/resource.rb'
    - 'lib/frontman/commands/serve.rb'
    - 'lib/frontman/commands/links.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/frontman/resource.rb'
    - 'lib/frontman/commands/serve.rb'
    - 'lib/frontman/commands/links.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'spec/**/*'
    - 'lib/frontman/helpers/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'lib/frontman/app.rb'

Lint/HandleExceptions:
  Exclude:
    - 'lib/frontman/commands/serve.rb'

Style/GlobalVars:
  Exclude:
    - 'lib/frontman/commands/links.rb'