version: 2.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string

    working_directory: ~/repo
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Lint code
          command: |
            bundle exec rubocop

      - run:
          name: Check types
          command: |
            bundle exec srb tc . --ignore=/vendor

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version: ["2.4", "2.5", "2.6", "2.7", "3.0"]
