# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
